### ISSUE TITLE
(Hallow's End) Control-Right-click to set waypoints to every bucket.

### ISSUE THREAD

**Issue by traceofwind** [EthanCentaurai/HandyNotes_HallowsEnd#1]
Control-Right-click to set waypoints to every bucket produces this error messages every time:

`Message: ...es\Libs\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers
Time: 10/23/17 11:29:39
Count: 1
Stack: ...es\Libs\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers
[string "safecall Dispatcher[5]"]:9: in function <[string "safecall Dispatcher[5]"]:5>
(tail call): ?
Interface\AddOns\HandyNotes\HandyNotes.lua:193: in function <Interface\AddOns\HandyNotes\HandyNotes.lua:192>

Locals: <none>`

`Message: ...es\Libs\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers
Time: 10/23/17 11:31:21
Count: 3
Stack: ...es\Libs\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers

Locals: <none>`

**Comment by traceofwind** [comment]
`Message: ...\AddOns\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers
Time: 10/23/17 11:40:04
Count: 1
Stack: ...\AddOns\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers
[C]: in function `error'
...\AddOns\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:456: in function `AddMinimapIconMF'
Interface\AddOns\TomTom\TomTom_Waypoints.lua:164: in function `SetWaypoint'
Interface\AddOns\TomTom\TomTom.lua:934: in function `AddMFWaypoint'
Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:89: in function <Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:85>
Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:97: in function <Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:93>
Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:106: in function <Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:103>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[5]"]:9: in function <[string "safecall Dispatcher[5]"]:5>
(tail call): ?
Interface\AddOns\HandyNotes\HandyNotes.lua:193: in function <Interface\AddOns\HandyNotes\HandyNotes.lua:192>

Locals: <none>`

**Comment by traceofwind** [comment]
Message: ...\AddOns\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers
Time: 10/23/17 11:50:58
Count: 1
Stack: ...\AddOns\HereBeDragons-1.0-33\HereBeDragons-Pins-1.0-16.lua:456: HereBeDragons-Pins-1.0: AddMinimapIconMF: 'mapID', 'x' and 'y' must be numbers
[C]: in function `error'
...\AddOns\HereBeDragons-1.0\HereBeDragons-Pins-1.0.lua:456: in function `AddMinimapIconMF'
Interface\AddOns\TomTom\TomTom_Waypoints.lua:164: in function `SetWaypoint'
Interface\AddOns\TomTom\TomTom.lua:934: in function `AddMFWaypoint'
Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:89: in function <Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:85>
Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:97: in function <Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:93>
Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:106: in function <Interface\AddOns\HandyNotes_HallowsEnd\Core.lua:103>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[5]"]:9: in function <[string "safecall Dispatcher[5]"]:5>
(tail call): ?
Interface\AddOns\HandyNotes\HandyNotes.lua:193: in function <Interface\AddOns\HandyNotes\HandyNotes.lua:192>

Locals: <none>

**Comment by EthanCentaurai** [comment]
Should be fixed now. Thank you. :)
