### ISSUE TITLE
Issue to set waypoint with TomTom

### ISSUE THREAD

**Issue by adrianobrum** [EthanCentaurai/HandyNotes_HallowsEnd#2]
Date: 2018-10-18 17:54:54
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\HandyNotes_HallowsEnd\Core.lua line 86:
   attempt to call method 'AddMFWaypoint' (a nil value)
Debug:
   HandyNotes_HallowsEnd\Core.lua:86:
      HandyNotes_HallowsEnd\Core.lua:81
   HandyNotes_HallowsEnd\Core.lua:97:
      HandyNotes_HallowsEnd\Core.lua:93
   HandyNotes_HallowsEnd\Core.lua:106:
      HandyNotes_HallowsEnd\Core.lua:103
   [C]: ?
   HandyNotes\HandyNotes.lua:59:
      HandyNotes\HandyNotes.lua:54
   HandyNotes\HandyNotes.lua:175: OnClick()
   HandyNotes\HandyNotes.lua:394: OnMouseUp()
   ...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:119:
      ...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:118
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BadBoy, vv8.0.7
  BagBrother, v
  Bagnon, v8.0.7
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  DBMCore, v8.0.13
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  HandyNotes, vv1.5.3
  HandyNotesHallowsEnd, vv1.3
  Informant, v8.0.6159 (SwimmingSeadragon)
  PersonalLootHelper, v2.17
  RaiderIO, v8.0.1 (v201810180600)
  RaiderIODBEUA, v
  RaiderIODBEUH, v
  Recount, vv8.0.1c
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TomTom, vv80001-1.0.2
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=3b2)

**Comment by EthanCentaurai** [comment]
Working on it now, but it's going to take a while. Please bare with me.

**Comment by EthanCentaurai** [comment]
Please download v1.4-beta1 and let me know if the issue persists.

**Comment by adrianobrum** [comment]
Yeah, it is working now. I thought that will put the closest waypoint in
the crazy Arrow but not. If I found another problem I will let you know.

Thanks for your time and dedication.

A quinta, 18/10/2018, 22:08, Ethan Centaurai <notifications@github.com>
escreveu:
