### ISSUE TITLE
EK Issues

### ISSUE THREAD

**Issue by MysticalOS** [EthanCentaurai/HandyNotes_HallowsEnd#3]
Eastern Kingdoms issues I remember
getting bucket in highbank (twlight highlands) doesn't clear bucket from map after completed
bucket in sentinal hill is in wrong location
bucket in harborage in dustwallow marsh isn't on continent map

there were 1-2 others but I forgot them.

**Comment by EthanCentaurai** [comment]
I'll investigate the Highbank one after work tonight. It could just be the API not keeping up though.

Sentinel Hill is a bizarre one as it is in one of two places depending on your quest progress. I broke that check earlier. 😓

The Harborage appears to be working fine here though.

**Comment by MysticalOS** [comment]
harborage was working on local map, but if you had continent one open to eastern K it was missing for me

**Comment by EthanCentaurai** [comment]
Do you have the latest versions of everything? HandyNotes or HereBeDragons-2.0 might be missing data.

![wowscrnshot_102018_221453](https://user-images.githubusercontent.com/8914/47260546-9fcd4880-d4b5-11e8-97ea-d8cb87f1f028.jpg)
