### ISSUE TITLE
Wotlk Dalaran issue

### ISSUE THREAD

**Issue by Stanzilla** [EthanCentaurai/HandyNotes_HallowsEnd#6]
Wotlk Dalaran shows the Alliance bucket as available to the horde running version 1.4.1

**Comment by EthanCentaurai** [comment]
You're confusing the neutral one in the Underbelly.

**Comment by Stanzilla** [comment]
Oh. Well that actually makes sense, can you put notes on the tooltip maybe?

**Comment by EthanCentaurai** [comment]
Yup, doing that now.
